config/routes.rb
Disicc::Application.routes.draw do
  resources :users
  resources :page
  resources :sequences
  resources :a_asequencs
  
  resources :alignments do
    member do
      get :display_annotated_alignment
      get :display_compensatory_annotated_alignment
      get :display_disorder_annotated_alignment
      get :calculate_intraresidue_consensus
    end
    collection do
      get :upload
      post :pre_process_fasta_file 
      post :process_fasta_file 
      post :complete_process_fasta_file 
    end
  end
 
  resources :alignment_positions
  resources :caps
  resources :classifications
  resources :conseqs
  resources :disorder_type
  resources :disorders
  resources :disorder_values
  resources :intra_residue_contacts
  resources :xdets

  root :to => "page#index"

end

app/models/disorder_value.rb
class DisorderValue
  include DataMapper::Resource
  
  property :disorder_value_id, Serial
  property :disorder_id, Integer, :required => true
  property :aasequence_id, Integer, :required => true
  property :dvalue, Float, :required => true

  belongs_to :disorder, 'Disorder', :parent_key => [:disorder_id], :child_key => [:disorder_id]  
  belongs_to :aasequence, 'AAsequence',  :parent_key => [:AAsequence_id], :child_key=>[:aasequence_id]
end

app/controllers/disorder_values_controller.rb
class DisorderValuesController < ApplicationController
  # GET /disorder_values
  # GET /disorder_values.xml
  def index
    @disorder_values = DisorderValue.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @disorder_values }
    end
  end

  # GET /disorder_values/1
  # GET /disorder_values/1.xml
  def show
    @disorder_value = DisorderValue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @disorder_value }
    end
  end

  # GET /disorder_values/new
  # GET /disorder_values/new.xml
  def new
    @disorder_value = DisorderValue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @disorder_value }
    end
  end

  # GET /disorder_values/1/edit
  def edit
    @disorder_value = DisorderValue.find(params[:id])
  end

  # POST /disorder_values
  # POST /disorder_values.xml
  def create
    @disorder_value = DisorderValue.new(params[:disorder_value])

    respond_to do |format|
      if @disorder_value.save
        format.html { redirect_to(@disorder_value, :notice => 'Disorder value was successfully created.') }
        format.xml  { render :xml => @disorder_value, :status => :created, :location => @disorder_value }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @disorder_value.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /disorder_values/1
  # PUT /disorder_values/1.xml
  def update
    @disorder_value = DisorderValue.find(params[:id])

    respond_to do |format|
      if @disorder_value.update_attributes(params[:disorder_value])
        format.html { redirect_to(@disorder_value, :notice => 'Disorder value was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @disorder_value.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /disorder_values/1
  # DELETE /disorder_values/1.xml
  def destroy
    @disorder_value = DisorderValue.find(params[:id])
    @disorder_value.destroy

    respond_to do |format|
      format.html { redirect_to(disorder_values_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/disorder_values_helper.rb
module DisorderValuesHelper
end

app/views/disorder_values/_form.html.erb
<%= form_for(@disorder_value) do |f| %>
  <% if @disorder_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disorder_value.errors.count, "error") %> prohibited this disorder_value from being saved:</h2>

      <ul>
      <% @disorder_value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disorder_values/edit.html.erb
<h1>Editing disorder_value</h1>

<%= render 'form' %>

<%= link_to 'Show', @disorder_value %> |
<%= link_to 'Back', disorder_values_path %>

app/views/disorder_values/index.html.erb
<h1>Listing disorder_values</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @disorder_values.each do |disorder_value| %>
  <tr>
    <td><%= link_to 'Show', disorder_value %></td>
    <td><%= link_to 'Edit', edit_disorder_value_path(disorder_value) %></td>
    <td><%= link_to 'Destroy', disorder_value, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Disorder value', new_disorder_value_path %>

app/views/disorder_values/new.html.erb
<h1>New disorder_value</h1>

<%= render 'form' %>

<%= link_to 'Back', disorder_values_path %>

app/views/disorder_values/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_disorder_value_path(@disorder_value) %> |
<%= link_to 'Back', disorder_values_path %>