config/routes.rb
Disicc::Application.routes.draw do
  resources :users
  resources :page
  resources :sequences
  resources :a_asequencs
  
  resources :alignments do
    member do
      get :display_annotated_alignment
      get :display_compensatory_annotated_alignment
      get :display_disorder_annotated_alignment
      get :calculate_intraresidue_consensus
    end
    collection do
      get :upload
      post :pre_process_fasta_file 
      post :process_fasta_file 
      post :complete_process_fasta_file 
    end
  end
 
  resources :alignment_positions
  resources :caps
  resources :classifications
  resources :conseqs
  resources :disorder_type
  resources :disorders
  resources :disorder_values
  resources :intra_residue_contacts
  resources :xdets

  root :to => "page#index"

end

app/models/intra_residue_contact.rb
class IntraResidueContact
  include DataMapper::Resource
  
  property :intra_residue_contact_id, Serial
  property :seq_id, Integer, :required => true
  property :first_residue, Integer, :required => true
  property :second_residue, Integer, :required => true
  property :confidence, Float, :required => true
  property :type, String, :required => true

  

end

app/controllers/intra_residue_contacts_controller.rb
class IntraResidueContactsController < ApplicationController
  # GET /intra_residue_contacts
  # GET /intra_residue_contacts.xml
  def index
    @intra_residue_contacts = IntraResidueContact.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @intra_residue_contacts }
    end
  end

  # GET /intra_residue_contacts/1
  # GET /intra_residue_contacts/1.xml
  def show
    @intra_residue_contact = IntraResidueContact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @intra_residue_contact }
    end
  end

  # GET /intra_residue_contacts/new
  # GET /intra_residue_contacts/new.xml
  def new
    @intra_residue_contact = IntraResidueContact.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @intra_residue_contact }
    end
  end

  # GET /intra_residue_contacts/1/edit
  def edit
    @intra_residue_contact = IntraResidueContact.find(params[:id])
  end

  # POST /intra_residue_contacts
  # POST /intra_residue_contacts.xml
  def create
    @intra_residue_contact = IntraResidueContact.new(params[:intra_residue_contact])

    respond_to do |format|
      if @intra_residue_contact.save
        format.html { redirect_to(@intra_residue_contact, :notice => 'Intra residue contact was successfully created.') }
        format.xml  { render :xml => @intra_residue_contact, :status => :created, :location => @intra_residue_contact }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @intra_residue_contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /intra_residue_contacts/1
  # PUT /intra_residue_contacts/1.xml
  def update
    @intra_residue_contact = IntraResidueContact.find(params[:id])

    respond_to do |format|
      if @intra_residue_contact.update_attributes(params[:intra_residue_contact])
        format.html { redirect_to(@intra_residue_contact, :notice => 'Intra residue contact was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @intra_residue_contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /intra_residue_contacts/1
  # DELETE /intra_residue_contacts/1.xml
  def destroy
    @intra_residue_contact = IntraResidueContact.find(params[:id])
    @intra_residue_contact.destroy

    respond_to do |format|
      format.html { redirect_to(intra_residue_contacts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/intra_residue_contacts_helper.rb
module IntraResidueContactsHelper
end

app/views/intra_residue_contacts/_form.html.erb
<%= form_for(@intra_residue_contact) do |f| %>
  <% if @intra_residue_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intra_residue_contact.errors.count, "error") %> prohibited this intra_residue_contact from being saved:</h2>

      <ul>
      <% @intra_residue_contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/intra_residue_contacts/edit.html.erb
<h1>Editing intra_residue_contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @intra_residue_contact %> |
<%= link_to 'Back', intra_residue_contacts_path %>

app/views/intra_residue_contacts/index.html.erb
<h1>Listing intra_residue_contacts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @intra_residue_contacts.each do |intra_residue_contact| %>
  <tr>
    <td><%= link_to 'Show', intra_residue_contact %></td>
    <td><%= link_to 'Edit', edit_intra_residue_contact_path(intra_residue_contact) %></td>
    <td><%= link_to 'Destroy', intra_residue_contact, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Intra residue contact', new_intra_residue_contact_path %>

app/views/intra_residue_contacts/new.html.erb
<h1>New intra_residue_contact</h1>

<%= render 'form' %>

<%= link_to 'Back', intra_residue_contacts_path %>

app/views/intra_residue_contacts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_intra_residue_contact_path(@intra_residue_contact) %> |
<%= link_to 'Back', intra_residue_contacts_path %>