config/routes.rb
Disicc::Application.routes.draw do
  resources :users
  resources :page
  resources :sequences
  resources :a_asequencs
  
  resources :alignments do
    member do
      get :display_annotated_alignment
      get :display_compensatory_annotated_alignment
      get :display_disorder_annotated_alignment
      get :calculate_intraresidue_consensus
    end
    collection do
      get :upload
      post :pre_process_fasta_file 
      post :process_fasta_file 
      post :complete_process_fasta_file 
    end
  end
 
  resources :alignment_positions
  resources :caps
  resources :classifications
  resources :conseqs
  resources :disorder_type
  resources :disorders
  resources :disorder_values
  resources :intra_residue_contacts
  resources :xdets

  root :to => "page#index"

end

app/models/xdet.rb
class Xdet
  include DataMapper::Resource
  
  property :xdet_id, Serial
  property :aasequence_id, Integer, :required => true
  property :conservation, Float, :required => true
  property :correlation, Float, :required => true

  

end

app/controllers/xdets_controller.rb
class XdetsController < ApplicationController
  # GET /xdets
  # GET /xdets.xml
  def index
    @xdets = Xdet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @xdets }
    end
  end

  # GET /xdets/1
  # GET /xdets/1.xml
  def show
    @xdet = Xdet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @xdet }
    end
  end

  # GET /xdets/new
  # GET /xdets/new.xml
  def new
    @xdet = Xdet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @xdet }
    end
  end

  # GET /xdets/1/edit
  def edit
    @xdet = Xdet.find(params[:id])
  end

  # POST /xdets
  # POST /xdets.xml
  def create
    @xdet = Xdet.new(params[:xdet])

    respond_to do |format|
      if @xdet.save
        format.html { redirect_to(@xdet, :notice => 'Xdet was successfully created.') }
        format.xml  { render :xml => @xdet, :status => :created, :location => @xdet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @xdet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /xdets/1
  # PUT /xdets/1.xml
  def update
    @xdet = Xdet.find(params[:id])

    respond_to do |format|
      if @xdet.update_attributes(params[:xdet])
        format.html { redirect_to(@xdet, :notice => 'Xdet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @xdet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /xdets/1
  # DELETE /xdets/1.xml
  def destroy
    @xdet = Xdet.find(params[:id])
    @xdet.destroy

    respond_to do |format|
      format.html { redirect_to(xdets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/xdets_helper.rb
module XdetsHelper
end

app/views/xdets/_form.html.erb
<%= form_for(@xdet) do |f| %>
  <% if @xdet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@xdet.errors.count, "error") %> prohibited this xdet from being saved:</h2>

      <ul>
      <% @xdet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xdets/edit.html.erb
<h1>Editing xdet</h1>

<%= render 'form' %>

<%= link_to 'Show', @xdet %> |
<%= link_to 'Back', xdets_path %>

app/views/xdets/index.html.erb
<h1>Listing xdets</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @xdets.each do |xdet| %>
  <tr>
    <td><%= link_to 'Show', xdet %></td>
    <td><%= link_to 'Edit', edit_xdet_path(xdet) %></td>
    <td><%= link_to 'Destroy', xdet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Xdet', new_xdet_path %>

app/views/xdets/new.html.erb
<h1>New xdet</h1>

<%= render 'form' %>

<%= link_to 'Back', xdets_path %>

app/views/xdets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_xdet_path(@xdet) %> |
<%= link_to 'Back', xdets_path %>