config/routes.rb
Disicc::Application.routes.draw do
  resources :users
  resources :page
  resources :sequences
  resources :a_asequencs
  
  resources :alignments do
    member do
      get :display_annotated_alignment
      get :display_compensatory_annotated_alignment
      get :display_disorder_annotated_alignment
      get :calculate_intraresidue_consensus
    end
    collection do
      get :upload
      post :pre_process_fasta_file 
      post :process_fasta_file 
      post :complete_process_fasta_file 
    end
  end
 
  resources :alignment_positions
  resources :caps
  resources :classifications
  resources :conseqs
  resources :disorder_type
  resources :disorders
  resources :disorder_values
  resources :intra_residue_contacts
  resources :xdets

  root :to => "page#index"

end

app/controllers/alignments_controller.rb
class AlignmentsController < ApplicationController
  # GET /alignments
  # GET /alignments.xml
  def index
    @alignments = Alignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @alignments }
    end
  end

  # GET /alignments/1
  # GET /alignments/1.xml
  def show
    @alignment = Alignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @alignment }
    end
  end

  # GET /alignments/new
  # GET /alignments/new.xml
  def new
    @alignment = Alignment.new
    @seq_types = {:N=>"N", :L=>"L", :P => "P", "P Cut"=> "P Cut"}
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @alignment }
    end
  end

  # GET /alignments/1/edit
  def edit
    @alignment = Alignment.find(params[:id])
  end

  # POST /alignments
  # POST /alignments.xml
  def create
    @alignment = Alignment.new(params[:alignment])

    respond_to do |format|
      if @alignment.save
        format.html { redirect_to(@alignment, :notice => 'Alignment was successfully created.') }
        format.xml  { render :xml => @alignment, :status => :created, :location => @alignment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @alignment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /alignments/1
  # PUT /alignments/1.xml
  def update
    @alignment = Alignment.find(params[:id])

    respond_to do |format|
      if @alignment.update_attributes(params[:alignment])
        format.html { redirect_to(@alignment, :notice => 'Alignment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alignment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /alignments/1
  # DELETE /alignments/1.xml
  def destroy
    @alignment = Alignment.find(params[:id])
    @alignment.destroy

    respond_to do |format|
      format.html { redirect_to(alignments_url) }
      format.xml  { head :ok }
    end
  end
  
  def residue_color(dis_avg, con_avg)
    if con_avg > 0.75
      if dis_avg >= 0.5
       @color = "00FF00"  #3394560  3CF3C0
      else
       @color =  "66FFCC" #6750156  66FFCC
      end
    else  #color for disorder only
      if dis_avg >= 0.5 && dis_avg < 0.6
       @color = "FFFF00" #16776960  FFFF00
      elsif dis_avg >= 0.6 && dis_avg < 0.7
       @color =  "FFCC00" #16763904  FFCC00
      elsif dis_avg >= 0.7 && dis_avg < 0.8
       @color =  "FF9900" #16750848  FF9900
      elsif dis_avg >= 0.8 && dis_avg < 0.9
       @color = "FF6600"  #16737792  FF6600
      elsif dis_avg >= 0.9
       @color =  "FF0000" #16711680  FF0000
      else
       @color = "999999"
      end
    end
    return @color
  end
  
  def alignment_to_positions(alignment)
    counter = 0
    alignment.alignment_sequence.each_char do |aa|
      if aa != "-"
        aaseq = AAsequence.first(:seq_id=>alignment.seq_id, :original_position=> counter)
        if !aaseq.nil?
          AlignmentPosition.create(:alignment_id => alignment.align_id,
                            :position => counter,
                            :aasequence_id => aaseq.AAsequence_id)
        end
      end
      counter +=1
    end
  end
  
  def upload
    @seq_types = {:N=>"N", :L=>"L", :P => "P"}
  end
  
  def pre_process_fasta_file
    @name = Time.now.to_s + params[:datafile].original_filename
    directory = "temp_data"
    @new_file = File.join(directory,@name)
    @alignment_name = params[:alignment_name]
    @seq_type = params[:seq_type]
  
      sequences = Sequence.all(:seq_type => @seq_type)
    
    @seq_options = Hash.new
    sequences.map{|k| @seq_options = @seq_options.merge({k.seq_name => k.seq_id.to_s})}
    File.open(@new_file, "wb"){ |f| f.write(params['datafile'].read)}
    logger.debug "HELLYEAH"
    begin
      file = File.new(@new_file, "r")
      @fasta_name_arrays = Array.new
      while (line = file.gets)
        if line.count(">") > 0
          @fasta_name_arrays << line.gsub(">", "")
        end
      end
      file.close
      rescue => err
          puts "Exception: #{err}"
          err
    end
  end
  
  
  def complete_process_fasta_file
    directory = "temp_data"
    @new_file = File.join(directory,params[:datafile_name])
    logger.debug "BEFORE*************************"
    begin
      file = File.new(@new_file, "r")
      logger.debug "After FILE OPEN"
      puts "After FILE OPEN"
      counter = 0
      order_count = 0
      abrev_name = ""
      alignment_sequence = ""
      fasta_hash = Hash.new
      logger.debug "BEFORE FASTA HASH*****"
      puts "BEFORE FASTA HASH*****"
      logger.debug "BEFORE@1232132131****"
      range = params[:seq_num].to_i - 1
      logger.debug "BEFORE FASTA RANGE***********"
      puts "BEFORE FASTA RANGE***********"
      (0..range).each do |i|
        logger.debug "BLAH"
        fasta_hash = fasta_hash.merge(params["fasta_name"+i.to_s].strip => params["seq"+i.to_s])
      end
      logger.debug {fasta_hash}
      logger.debug "AFTER FASTA HASH*******"
      while (line = file.gets)
        if line.count(">") > 0 && counter > 0
          #save the current sequence to an alignment
          logger.debug {fasta_hash[abrev_name]}
          puts fasta_hash[abrev_name]
          @sequence = Sequence.get(fasta_hash[abrev_name.strip])
          logger.debug "After"
          puts "After"  
          logger.debug "OHNO NONONONONO" 
          @alignment = Alignment.new(:seq_id => @sequence.seq_id,
                           :alignment_name => params[:alignment_name],
                           :align_order => order_count,
                           :alignment_sequence => alignment_sequence,
                           :fasta_title => abrev_name)
           logger.debug "SHAZZZZZAAAAAAAM"                 
          logger.debug { @alignment.valid?}
          if !@alignment.valid?
            puts @alignment.errors.inspect()
          end
          logger.debug "VALID"
          logger.debug { @alignment.errors.inspect }
          @alignment.save
          alignment_to_positions(@alignment)              
          #this is the sequene label
          abrev_name = line.gsub(">", "")

          order_count += 1
          alignment_sequence = ""
        elsif line.count(">") > 0
          abrev_name = line.gsub(">","")
          logger.debug { abrev_name }
          alignment_sequence =""
        elsif counter > 0
          alignment_sequence = alignment_sequence + line.lstrip.rstrip
        end
        counter = counter + 1
      end
       puts fasta_hash[abrev_name]
        @sequence = Sequence.get(fasta_hash[abrev_name.strip])
        logger.debug "After"
        puts "After"  
        logger.debug "OHNO NONONONONO" 
        @alignment = Alignment.new(:seq_id => @sequence.seq_id,
                         :alignment_name => params[:alignment_name],
                         :align_order => order_count,
                         :alignment_sequence => alignment_sequence,
                         :fasta_title => abrev_name)
         logger.debug "SHAZZZZZAAAAAAAM"                 
        logger.debug { @alignment.valid?}
        if !@alignment.valid?
          puts @alignment.errors.inspect()
        end
        logger.debug "VALID"
        logger.debug { @alignment.errors.inspect }
        @alignment.save
        alignment_to_positions(@alignment)              
        #this is the sequene label
        abrev_name = line.gsub(">", "")

        order_count += 1
        alignment_sequence = ""
      file.close
      rescue => err
          puts "Exception: #{err}"
          err
    end
    redirect_to(alignments_path)
  end
  
  
  
  def process_fasta_file
    name = Time.now.to_s + params[:datafile_name]#.original_filename
    directory = "temp_data"
    @new_file = File.join(directory,params[:datafile_name])
    File.open(@new_file, "wb"){ |f| f.write(params['datafile_name'])}
    logger.debug "HELLYEAH"
    begin
      file = File.new(@new_file, "r")
      counter = 0
      order_count = 0
      abrev_name = ""
      alignment_sequence = ""
      while (line = file.gets)
        if line.count(">") > 0 && counter > 0
          #save the current sequence to an alignment
          logger.debug { alignment_sequence }
          logger.debug "Before"
          if abrev_name.count("/") > 0
            abrev_name = abrev_name.split("/")[0]
          end
          @sequence = Sequence.first(:abrev_name => abrev_name.lstrip.rstrip, :seq_type => params[:seq_type])
          logger.debug "After"
          logger.debug { @sequence.to_s}
          logger.debug "OHNO" 
          @alignment = Alignment.new(:seq_id => @sequence.seq_id,
                           :alignment_name => params[:alignment_name],
                           :align_order => order_count,
                           :alignment_sequence => alignment_sequence)
          @alignment.valid?
          logger.debug "VALID"
          logger.debug { @alignment.errors.inspect }
          @alignment.save
          alignment_to_positions(@alignment)              
          #this is the sequene label
          abrev_name = line.gsub(">", "")

          order_count += 1
          alignment_sequence = ""
        elsif line.count(">") > 0
          abrev_name = line.gsub(">","")
          logger.debug { abrev_name }
          alignment_sequence =""
        elsif counter > 0
          alignment_sequence = alignment_sequence + line.lstrip.rstrip
        end
        counter = counter + 1
      end
      file.close
      rescue => err
          puts "Exception: #{err}"
          err
    end
    redirect_to(alignments_path)
  end
  
  
  def calculate_intraresidue_consensus
    Alignment.all(:alignment_name => Alignment.get(params[:id]).alignment_name, :order => [:align_order.asc]).each do |alignment|

app/helpers/alignments_helper.rb
module AlignmentsHelper
end

app/views/alignments/_form.html.erb
<%= form_for(@alignment) do |f| %>
  <% if @alignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alignment.errors.count, "error") %> prohibited this alignment from being saved:</h2>

      <ul>
      <% @alignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alignments/display_annotated_alignment.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<% (0..@ranges).each do |i| %>
  <table>
    <%- @display_array.each do |seq| %>
      <tr>
        <td><%= seq["name"] %></td>
        <%- #seq["alignment"].each do |residue| %>
        <%- ((i*@aa_length)..(i*@aa_length+@aa_length-1)).each do |r|  %>
          <% if seq["alignment"].length > r %>
            <td align = "center" bgcolor = #<%= seq["alignment"][r]%>>&nbsp</td>
          <%-end%>
        <%- end %>
      </tr>
    <%- end %>
    <!--<tr>
     <td>"Contact Consensus"</td>
     <%-  @contact_consensus_array.each do |con| %>
       <td><%=con%></td>
     <%- end %>
    </tr>--!>
  </table>
  <br>
  <br>
  <br>
  <br>
<% end %>
<br>
Total Number of Sequences in Alignment: <%=@display_array.length-1%>
<br>
Total Number of Sequences with Contacts: <%=@seq_contact_count%>
<br><br>
<table>
  <%-  @contact_consensus_array.length.times do |i| %>
    <tr>
      <td><%= i%></td>
      <td><%= @contact_consensus_array[i] %></td>
      <% num =  @contact_consensus_array[i].to_f / @seq_contact_count #@display_array.length.to_f %>
      <td><%= num %></td>
    </tr>  
  <%- end %>
</table>  
<%= link_to 'Back', alignments_path %>

app/views/alignments/display_compensatory_annotated_alignment.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<% (0..@ranges).each do |i| %>
  <table>
    <%- @display_array.each do |seq| %>
      <tr>
        <td><%= seq["name"] %></td>
        <%- #seq["alignment"].each do |residue| %>
        <%- ((i*@aa_length)..(i*@aa_length+@aa_length-1)).each do |r|  %>
          <% if seq["alignment"].length > r %>
            <td align = "center" bgcolor = #<%= seq["alignment"][r]%>>&nbsp</td>
          <%-end%>
        <%- end %>
      </tr>
    <%- end %>
    <!--<tr>
     <td>"Contact Consensus"</td>
     <%-  @contact_consensus_array.each do |con| %>
       <td><%=con%></td>
     <%- end %>
    </tr>--!>
  </table>
  <br>
  <br>
  <br>
  <br>
<% end %>
<br>
Total Number of Sequences in Alignment: <%=@display_array.length-1%>
<br>
Total Number of Sequences with Contacts: <%=@seq_contact_count%>
<br><br>
<table>
  <%-  @contact_consensus_array.length.times do |i| %>
    <tr>
      <td><%= i%></td>
      <td><%= @contact_consensus_array[i] %></td>
      <% num =  @contact_consensus_array[i].to_f / @seq_contact_count #@display_array.length.to_f %>
      <td><%= num %></td>
    </tr>  
  <%- end %>
</table>  
<%= link_to 'Back', alignments_path %>

app/views/alignments/display_disorder_annotated_alignment.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<% (0..@ranges).each do |i| %>
  <table>
    <%- @display_array.each do |seq| %>
      <tr>
        <td><%= seq["name"] %></td>
        <%- #seq["alignment"].each do |residue| %>
        <%- ((i*@aa_length)..(i*@aa_length+@aa_length-1)).each do |r|  %>
          <% if seq["alignment"].length > r %>
            <td align = "center" bgcolor = #<%= seq["alignment"][r]%>>&nbsp</td>
          <%-end%>
        <%- end %>
      </tr>
    <%- end %>
    <!--<tr>
     <td>"Contact Consensus"</td>
     <%-  @contact_consensus_array.each do |con| %>
       <td><%=con%></td>
     <%- end %>
    </tr>--!>
  </table>
  <br>
  <br>
  <br>
  <br>
<% end %>
<br>
Total Number of Sequences in Alignment: <%=@display_array.length-1%>
<br>
Total Number of Sequences with Contacts: <%=@seq_contact_count%>
<br><br>
<table>
  <%-  @contact_consensus_array.length.times do |i| %>
    <tr>
      <td><%= i%></td>
      <td><%= @contact_consensus_array[i] %></td>
      <% num =  @contact_consensus_array[i].to_f / @seq_contact_count #@display_array.length.to_f %>
      <td><%= num %></td>
    </tr>  
  <%- end %>
</table>  
<%= link_to 'Back', alignments_path %>

app/views/alignments/edit.html.erb
<h1>Editing alignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @alignment %> |
<%= link_to 'Back', alignments_path %>

app/views/alignments/index.html.erb
<h1>Listing alignments</h1>

<table>
  <tr>
    <%- @alignments.properties.each do |prop|-%>
      <th>
        <b><%= prop.name%>:</b>
      </th>
    <%- end -%>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alignments.each do |alignment| %>
  <tr>
    <%- @alignments.properties.each do |prop|-%>
    <td>
      <%= link_to alignment[prop.name], display_annotated_alignment_alignment_path(alignment.align_id) %>
    </td>
    <%- end -%>
    <td>
      <%= link_to "Compensatory", display_compensatory_annotated_alignment_alignment_path(alignment.align_id) %>
    </td>
    <td>
      <%= link_to "Disorder", display_disorder_annotated_alignment_alignment_path(alignment.align_id) %>
    </td>
    <td><%= link_to 'Show', alignment %></td>
    <td><%= link_to 'Edit', edit_alignment_path(alignment) %></td>
    <td><%= link_to 'Destroy', alignment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alignment', new_alignment_path %>
<%= link_to 'Back', root_path %>

app/views/alignments/new.html.erb
<h2>Add New Alignment</h2>
<%= form_tag "pre_process_fasta_file", :multipart => true do%>
  
  <div class="actions">
  Alignment Name:
  <%= text_field_tag("alignment_name") %>
  <br>
  Sequence Type:
  <%= select_tag("seq_type", options_for_select(@seq_types)) %>
  <br>
  Fasta File to upload(sequences are labeled with abrev names):
  <%= file_field_tag('datafile')%>
  <br><br>
    <%= submit_tag("Upload Alignment") %>
  </div>
<% end %>

<%= link_to 'Back', alignments_path %>

app/views/alignments/pre_process_fasta_file.html.erb
<h2>Assign the Correct Sequences</h2>
<%= form_tag "complete_process_fasta_file", :multipart => true do%>
  
  <div class="actions">
    Alignment Name:
    <%= @alignment_name %>
    <br>
    Sequence Type:
    <%= @seq_type %>
    <br>
    <table>
      <tr>
        <th> Fasta Sequence Title</th>
        <th> Database Sequence</th>
      </tr>
      <%- color = 1 %>
      <%- counter = 0 %>
    <%- @fasta_name_arrays.each do |fasta| %>
      <%- color = 1 - color%>
      <tr class = '<%= "row" + color.to_s %>'> 
        <td><%= fasta %></td>
        <td><%= select_tag("seq"+counter.to_s, options_for_select(@seq_options.sort)) %></td>
        <%= hidden_field_tag("fasta_name"+counter.to_s, fasta) %>
      </tr>
      <%-counter +=1%>
    <% end %>
    </table>
    <br><br>
      <%= submit_tag("Complete Alignment") %>
  </div>
  <%= hidden_field_tag("datafile_name", @name) %>
  <%= hidden_field_tag("alignment_name", @alignment_name) %>
  <%= hidden_field_tag("seq_type", @seq_type) %>
  <%= hidden_field_tag("seq_num", @fasta_name_arrays.length) %>
<%- end %>

<%= link_to 'Back', alignments_path %>

app/views/alignments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_alignment_path(@alignment) %> |
<%= link_to 'Back', alignments_path %>

app/views/alignments/upload.html.erb
<h2>Add New Alignment</h2>
<%= form_tag "process_fasta_file", :multipart => true do%>
  
  <div class="actions">
  Alignment Name:
  <%= text_field_tag("alignment_name") %>
  <br>
  Sequence Type:
  <%= select_tag("seq_type", options_for_select(@seq_types)) %>
  <br>
  Fasta File to upload(sequences are labeled with abrev names):
  <%= file_field_tag('datafile')%>
  <br><br>
    <%= submit_tag("Upload Alignment") %>
  </div>
<% end %>

<%= link_to 'Back', alignments_path %>